version: '3'
services:
  web:
    image: bsb99/living-by-myself-server:latest
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f https://tracelover.shop/home/communities"]
      interval: 5s
      timeout: 5s
      retries: 3

networks:
  my_network:
